# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180827_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='/static/images/logo.png', max_length=500),
        ),
    ]
