# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180827_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
